config/routes.rb
Rails.application.routes.draw do
    
  namespace :public do
    get 'chats/show'
  end
  root to: "homes#top"
  get "home/about"=>"homes#about"
  
   #ゲストユーザー用
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end   
 
 
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
    
    namespace :admin do
      
      resources :users, only: [:index, :show, :edit, :update]
      
      resources :diaries, only: [:index, :destroy] do
        resources :diary_comments, only: [:index, :destroy]
      end
      
      resources :rescued_cats, only: [:index, :destroy] do
        resources :rescued_cat_comments, only: [:index, :destroy]
      end
     
    end
    
   
   
    
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
    
    scope module: :public do
     
      get 'users/confirm_withdraw' => 'users#confirm_withdraw'
      patch 'users/withdraw' => 'users#withdraw'
      
      resources :users, only: [:show, :edit, :update] do
         member do
           get :favorites 
           get :bookmarks
           get :diaries
           get :cats
           get :rescued_cats
           get :my_page
           get :follows, :followers
         end
           resource :relationships, only: [:create, :destroy]
      end
      
      resources :chats, only: [:show, :create, :destroy]
      resources :cats, only: [:new, :create, :update, :show, :edit] 
      resources :notifications, only: [:update]
      
      resources :diaries do
         resource :favorite, only: [:create, :destroy]
         resources :diary_comments, only: [:create, :destroy]
          collection do
            get 'search'
            get 'tag_search'
          end
      end
      
      resources :rescued_cats do
         resource :bookmark, only: [:create, :destroy]
         resources :rescued_cat_comments, only: [:create, :destroy]
         collection do
            get 'search'
            get 'label_search'
         end
      end
   
      
    end 
 
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    @rescued_cats = RescuedCat.order(created_at: :desc).take(4) #新規順
    to = Time.current.at_end_of_day 
    from = (to - 6.day).at_beginning_of_day
    @diaries = Diary.includes(:favorited_users).#一週間のいいねがおおい順に表示
      sort_by {|x|
        x.favorited_users.includes(:favorites).where(created_at: from...to).size
      }.reverse
       .take(3)
 
    @newdiaries = Diary.order(created_at: :desc).take(4) #新規順の投稿
    @tag_name = "おなやみ"
    @diary_questions = Diary.joins(:tags).where(tags: { name: @tag_name }).limit(4) #おなやみ相談の投稿
  end
  
  
  
  def about
  end
  
  
  
  
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="container text-center mt-5">
 
  <%= image_tag 'cat_koubakozuwari_brown.jpg', size: "200x200", class: "img-fluid " %>

  <h1>Purrfect Hubとは？</h1>
  <p>Purrfect Hub（パーフェクトハブ）は猫好きのための里親募集・日記投稿のできるコミュニティサイトです。</p>
  <p>purr（パー）は、猫ちゃんがリラックスする時に出すゴロゴロ音のことで、</p>
  <p>「Purrfect」は「Perfect（完璧）」をもじったスラングで、世界中の猫好きさんたちにSNSでよくハッシュタグとして使われています。</p>
  <p>Purrfect Hubは、全ての猫ちゃんが安心して幸せに暮らせることを願って作られたサイトです。</p>
  <p>猫の成長を記録したり、他の飼い主さんとコミュニケーションを取って悩みを共有することができます。</p>
  <p>もちろん猫ちゃんを飼っていない方もOKです！</p>
  <p>たくさん投稿して素敵な猫ライフを送りましょう！</p>


  <h2 class="mt-5">使い方</h2>
  <h3>①日記を投稿する</h3>
  <p>マイページから日記を投稿できます！</p>
  <p>My Catで自分の猫ちゃんを登録しておくと、日記に猫ちゃんを登録して</p>
  <p>猫ちゃん毎に日記を確認することができます！</p>
  <p>他のユーザーの投稿にいいねやコメントすることもできます。</p>

  <h3>②おなやみ投稿</h3>
  <p>猫ちゃんの飼育方法や病気についてのおなやみを投稿できます！</p>
  <p>日記の投稿にて、「おなやみ」でタグ付けをして投稿しましょう！</p>
  <p>コメントで誰かのおなやみに答えることもできます。</p>

  <h3>③里親募集</h3>
  <p>保護猫の情報を投稿し、里親さんを探すことができます。</p>
  <p>応募や譲渡はコメントやDMでやり取りしてください。</p>
  
  <h3 class="mt-5"><i class="fas fa-exclamation-triangle"></i>注意<i class="fas fa-exclamation-triangle"></i></h3>
  <h4>[日記・コメントの内容について]</h4>
  <p>客観的に誹謗中傷・名誉毀損であると判断される言動や暴力的な言葉使いはしないで下さい。</p>
  <p>発見次第、予告なしで投稿・コメントを削除する場合がありますので、予めご了承ください。</p>
  <p>悪質な場合は、アカウント削除処分も含めて厳しい対応を取らせていただきます。</p>

  <h4>[宣伝目的の投稿]</h4>
  <p>他サイトへ誘導するような明らかな商業目的な宣伝投稿に関しては、即時削除いたします。</p>
  <p>また、ペットの生体販売に関する宣伝投稿や販売目的と判断される投稿も即時削除します。</p>
  <p>著作権を侵害する画像の使用は見つけ次第、削除致しますのでご了承下さい。</p>

  <h4>[著作権について]</h4>
  <p>著作権を侵害する画像は使用しないで下さい。</p>
  <p>また、当サイトに投稿された記事・画像・情報などの無断転用は一切禁止します。</p>
  <p>著作権を侵害する画像の使用は見つけ次第、削除致しますのでご了承下さい。</p>

  <%= image_tag 'pet_cat_sit.jpg', size: "200x200", class: "img-fluid  mt-5" %>

</div>

app/views/homes/top.html.erb
<div class="container mt-4">
    <div class="row">
        <div class="col-12 text-center">
            <h3>Purrfect Hubへようこそ！</h3>
            <p class="lead">Purrfect Hub（パーフェクトハブ）は猫好きのための里親募集・日記投稿のできるコミュニティサイトです。</p>
        </div>
    </div>
  <h3 class = "text-center">里親募集中！</h3>
    <div class="col-12 text-right mt-4">
        <%= link_to "保護猫をさがす➡", rescued_cats_path, class: "btn btn-secondary" %>
    </div>
    <div class="row mt-4">
        
        <% @rescued_cats.each do |rescued_cat| %>
            <div class="col-md-3 mb-4">
                <div class="card">
                   
                        <div class="card-header text-center">
                          <%= link_to rescued_cat_path(rescued_cat.id) do %>
                            <p class="card-title"><%= truncate(rescued_cat.title, :length => 12) %></p>
                          <% end %>
                        </div>
                    

                    <% if rescued_cat.images.attached? %>
                        <%= link_to rescued_cat_path(rescued_cat.id) do %>
                            <%= image_tag rescued_cat.images.first, class: "card-img-top", alt: "Cat Image", size: "100x200" %>
                        <% end %>
                    <% end %>

                    <div class="card-body">
                        <p><%= render 'public/rescued_cats/label', rescued_cat: rescued_cat %></p>

                        <% if rescued_cat.name.present? %>
                            <p>名前：<%= rescued_cat.name %></p>
                        <% else %>
                            <p>名前：</p>
                        <% end %>

                        <p>性別：<%= rescued_cat.sex %></p>
                    </div>
                </div>
            </div>
        <% end %>
    </div>


    
      <div class="row mt-4">
            <div class="col-3 md-4 question">
                <div class="text-center h4">おなやみ相談コーナー</div>
                    <% @diary_questions.each do |diary| %>
                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title"><%= truncate(diary.title, :length => 12) %></h5>
                            <h8 class="card-body"><%= truncate(diary.body, :length => 30) %></h8>
                        </div>
                        <div class="card-footer">
                          <small class="text-left"><%= diary.user.nickname %>さんの投稿</small>
                          <div class="d-flex justify-content-end">
                            <p> <i class="far fa-comment "><%= diary.diary_comments.count %></i> </p>
                            <p class = "ml-3">
                              <div class="diaries_favorite_<%= diary.id %>">
                                <%= render 'public/diaries/favorite', diary: diary, current_user: current_user %>
                              </div>
                            </p>
                          </div>
                          <%= link_to "詳細を見る➡", diary_path(diary.id), class: "btn btn-primary" %>
                        </div>
                    </div>
                    <% end %>
                <div class="ml-auto">
                    <%= link_to "みんなのお悩み相談➡", tag_search_diaries_path(name: "おなやみ"), method: :get ,class: "btn btn-secondary" %>
                </div>      
            </div>
                
               <div class="col-md-6 diaries">
                   <div class="text-center h3">注目の日記</div>
                    <% @diaries.each do |diary| %>
                    <div class="card mb-4">
                        <% if diary.images.attached? %>
                           <%= link_to diary_path(diary.id) do %>
                              <%= image_tag diary.images.first, class: "card-img-top", alt: "Diary Image", size: "150x300" %>
                           <% end %>
                        <% end %>
                        <div class="card-body">
                            <%= link_to diary_path(diary.id) do %>
                              <h5 class="card-title"><%= truncate(diary.title, :length => 12) %></h5>
                            <% end %>
                        </div>
                        <div class="card-footer">
                            <small class="text-left"><%= diary.user.nickname %>さんの投稿</small>
                            <div class="d-flex justify-content-end">
                               <p> <i class="far fa-comment "><%= diary.diary_comments.count %></i> </p>
                               <p class = "ml-3">
                                 <div class="diaries_favorite_<%= diary.id %>">
                                   <%= render 'public/diaries/favorite', diary: diary, current_user: current_user %>
                                 </div>
                               </p>
                            </div>
                        </div>
                    </div>
                    <% end %>
            </div>
            
                <div class="col-3 md-4 question">
                    <div class="text-center h4">新しい投稿</div>
                       <% @newdiaries.each do |diary| %>
                        <div class="card mb-4">
                            <% if diary.images.attached? %>
                                <%= link_to diary_path(diary.id) do %>
                                  <%= image_tag diary.images.first, class: "card-img-top", alt: "Diary Image", size: "100x200" %>
                                <% end %>
                            <% end %>
                            <div class="card-body">
                                <%= link_to diary_path(diary.id) do %>
                                  <h6 class="card-title"><%= truncate(diary.title, :length => 12) %></h5>
                                <% end %>
                            </div>
                            <div class="card-footer">
                              <small class="text-left"><%= diary.user.nickname %>さんの投稿</small>
                                <div class="d-flex justify-content-end">
                                   <p> <i class="far fa-comment "><%= diary.diary_comments.count %></i> </p>
                                   <p class = "ml-3">
                                     <div class="diaries_favorite_<%= diary.id %>">
                                       <%= render 'public/diaries/favorite', diary: diary, current_user: current_user %>
                                     </div>
                                   </p>
                                </div>
                            </div>
                        </div>
                        <% end %>
                    <div class="text-center mt-3">
                        <%= link_to "みんなの日記を見る➡", diaries_path, class: "btn btn-secondary" %>
                    </div>
                </div>
    </div>
</div>