config/routes.rb
Rails.application.routes.draw do
    
  namespace :public do
    get 'chats/show'
  end
  root to: "homes#top"
  get "home/about"=>"homes#about"
  
   #ゲストユーザー用
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end   
 
 
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
    
    namespace :admin do
      
      resources :users, only: [:index, :show, :edit, :update]
      
      resources :diaries, only: [:index, :destroy] do
        resources :diary_comments, only: [:index, :destroy]
      end
      
      resources :rescued_cats, only: [:index, :destroy] do
        resources :rescued_cat_comments, only: [:index, :destroy]
      end
     
    end
    
   
   
    
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
    
    scope module: :public do
     
      get 'users/confirm_withdraw' => 'users#confirm_withdraw'
      patch 'users/withdraw' => 'users#withdraw'
      
      resources :users, only: [:show, :edit, :update] do
         member do
           get :favorites 
           get :bookmarks
           get :diaries
           get :cats
           get :rescued_cats
           get :my_page
           get :follows, :followers
         end
           resource :relationships, only: [:create, :destroy]
      end
      
      resources :chats, only: [:show, :create, :destroy]
      resources :cats, only: [:new, :create, :update, :show, :edit] 
      resources :notifications, only: [:update]
      
      resources :diaries do
         resource :favorite, only: [:create, :destroy]
         resources :diary_comments, only: [:create, :destroy]
          collection do
            get 'search'
            get 'tag_search'
          end
      end
      
      resources :rescued_cats do
         resource :bookmark, only: [:create, :destroy]
         resources :rescued_cat_comments, only: [:create, :destroy]
         collection do
            get 'search'
            get 'label_search'
         end
      end
   
      
    end 
 
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/diary.rb
class Diary < ApplicationRecord
    
    
    
 has_many_attached :images
 

 belongs_to :user
 belongs_to :cat, optional: true
 
 has_many :diary_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :favorited_users, through: :favorites, source: :user
 has_many :taggings, dependent: :destroy
 has_many :tags, through: :taggings
 
 has_many :notifications, as: :notifiable, dependent: :destroy
 
 scope :latest, -> { order(created_at: :desc) }  #latest = 新着順, desc = 降順
 scope :old, -> { order(created_at: :asc) }  #old = 古い順, asc = 昇順
 scope :most_favorited, -> { includes(:favorited_users)
   .sort_by { |x| x.favorited_users.includes(:favorites).size }.reverse } #most_favorited = いいね順(多い順)
 
 validates :title, length: {maximum: 30}, presence: true
 validates :body, length: {maximum: 3000}, presence: true
 
 enum weather: { sunny: 0, cloudy: 1, rainy: 2, snowy: 3, foggy: 4, typhoon: 5, thunder: 6 }
 
  def favorited_by?(user)
     return false if user.nil?
    favorites.exists?(user_id: user.id)
  end


  def create_tags(input_tags)
    input_tags.each do |tag|     # splitで分けたtagをeach文で取得する
     if tag.length <= 6      #6文字以内で作成 
        new_tag = Tag.find_or_create_by(name: tag)     # tagモデルに存在していれば、そのtagを使用し、なければ新規登録する
        tags << new_tag     # 登録するdiaryのtagに紐づける（中間テーブルにも反映される）
     end
    end
  end
  
  
  def update_tags(input_tags)
     registered_tags = tags.pluck(:name) # すでに紐付けれらているタグを配列化する
     new_tags = input_tags - registered_tags # 追加されたタグ
     destroy_tags = registered_tags - input_tags # 削除されたタグ
    
     new_tags.each do |tag| # 新しいタグをモデルに追加
      if tag.length <= 6  #6文字以内で作成
        new_tag = Tag.find_or_create_by(name: tag)
        tags << new_tag
      end
    end
    
     destroy_tags.each do |tag| # 削除されたタグを中間テーブルから削除
       tag_id = Tag.find_by(name: tag)
       destroy_tagging = Tagging.find_by(tag_id: tag_id, diary_id: id)
       destroy_tagging.destroy
     end
  end




end

app/controllers/admin/diaries_controller.rb
class Admin::DiariesController < ApplicationController
  def index
       @diaries = Diary.page(params[:page]).order(created_at: :desc)
  end

  def destroy
    diary = Diary.find(params[:id])
    diary.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to admin_diaries_path
  end

  private

  def diary_params
    params.require(:diary).permit(:cat_id, :user_id, :title, :body, :weight, images: [])
  end

end

app/helpers/admin/diaries_helper.rb
module Admin::DiariesHelper
end

app/views/admin/diaries/index.html.erb
<div class="container mt-5">

  <h1 class="text-center">日記一覧</h1>
  
    <h3 class = "text-right mb-3">
      <%= link_to "コメント一覧へ", admin_diary_diary_comments_path(:diary_id), class: "btn btn-sm btn-info" %>
    </h3>
   <div class="row">
    <% @diaries.each do |diary| %>
      <div class="col-md-3 mb-4">
        <div class="card">
          <div class="card-header text-center">
            <%= link_to diary_path(diary.id), class: "card-title" do %>
              <%= diary.title %>
            <% end %>
          </div>

          <% if diary.images.attached? %>
            <%= link_to diary_path(diary.id) do %>
              <%= image_tag diary.images.first, class: "card-img-top", alt: "Cat Image", size: "100x200" %>
            <% end %>
          <% end %>

          <div class="card-body">
            <p><%= image_tag diary.user.get_profile_image(50,50), class: "mr-3 rounded-circle" %>
              <%= link_to admin_user_path(diary.user.id) do %>
                <%= diary.user.nickname %>
               <% end %>
            </p>
            <small><%= truncate(diary.body, :length => 30) %></small>
            <p class = "justify-content-end">
             <%= link_to "削除", admin_diary_path(diary), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に削除しますか？" %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  


    <div class="row justify-content-center">
      <div class="col-4">
        <%= paginate @diaries %>
      </div>
    </div>

</div>
 