config/routes.rb
Rails.application.routes.draw do
    
  namespace :public do
    get 'chats/show'
  end
  root to: "homes#top"
  get "home/about"=>"homes#about"
  
   #ゲストユーザー用
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end   
 
 
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
    
    namespace :admin do
      
      resources :users, only: [:index, :show, :edit, :update]
      
      resources :diaries, only: [:index, :destroy] do
        resources :diary_comments, only: [:index, :destroy]
      end
      
      resources :rescued_cats, only: [:index, :destroy] do
        resources :rescued_cat_comments, only: [:index, :destroy]
      end
     
    end
    
   
   
    
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
    
    scope module: :public do
     
      get 'users/confirm_withdraw' => 'users#confirm_withdraw'
      patch 'users/withdraw' => 'users#withdraw'
      
      resources :users, only: [:show, :edit, :update] do
         member do
           get :favorites 
           get :bookmarks
           get :diaries
           get :cats
           get :rescued_cats
           get :my_page
           get :follows, :followers
         end
           resource :relationships, only: [:create, :destroy]
      end
      
      resources :chats, only: [:show, :create, :destroy]
      resources :cats, only: [:new, :create, :update, :show, :edit] 
      resources :notifications, only: [:update]
      
      resources :diaries do
         resource :favorite, only: [:create, :destroy]
         resources :diary_comments, only: [:create, :destroy]
          collection do
            get 'search'
            get 'tag_search'
          end
      end
      
      resources :rescued_cats do
         resource :bookmark, only: [:create, :destroy]
         resources :rescued_cat_comments, only: [:create, :destroy]
         collection do
            get 'search'
            get 'label_search'
         end
      end
   
      
    end 
 
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rescued_cat.rb
class RescuedCat < ApplicationRecord
    
 has_many_attached :images
 
 belongs_to :user
 
 has_many :rescued_cat_comments, dependent: :destroy
 has_many :bookmarks, dependent: :destroy
 has_many :labelings, dependent: :destroy
 has_many :labels, through: :labelings
 
 has_many :notifications, as: :notifiable, dependent: :destroy
  
 validates :name, length: {maximum: 20}
 validates :age, length: {maximum: 3000}, presence: true
 validates :sex, presence: true
 validates :title, length: {maximum: 30}, presence: true
 validates :body, length: {maximum: 3000}, presence: true
 validates :vaccine, length: {maximum: 100}, presence: true

  def bookmarked_by?(user)
    return false if user.nil?
    bookmarks.exists?(user_id: user.id)
  end

  def create_labels(input_labels)
    input_labels.each do |label|                     # splitで分けたlabelをeach文で取得する
      new_label = Label.find_or_create_by(name: label) # labelモデルに存在していれば、そlabelを使用し、なければ新規登録する
      labels << new_label                            # 登録するdiaryのlabelに紐づける（中間テーブルにも反映される）
    end
  end
  
  
  def update_labels(input_labels)
     registered_labels = labels.pluck(:name) # すでに紐付けれらているラベルを配列化する
     new_labels = input_labels - registered_labels # 追加されたラベル
     destroy_labels = registered_labels - input_labels # 削除されたラベル
    
     new_labels.each do |label| # 新しいラベルをモデルに追加
      new_label = Label.find_or_create_by(name: label)
      labels << new_label
     end
    
     destroy_labels.each do |label| # 削除されたラベルを中間テーブルから削除
       label_id = Label.find_by(name: label)
       destroy_labeling = Labeling.find_by(label_id: label_id, rescued_cat_id: id)
       destroy_labeling.destroy
     end
  end


end

app/controllers/admin/rescued_cats_controller.rb
class Admin::RescuedCatsController < ApplicationController
  def index
    @rescued_cats = RescuedCat.page(params[:page]).order(created_at: :desc)
  end
  

  def destroy
    rescued_cat = RescuedCat.find(params[:id])
    rescued_cat.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to admin_rescued_cats_path
  end
  
    private

  def rescued_cat_params
    params.require(:rescued_cat).permit(:user_id, :title, :body, :name, :sex, :age, :vaccine, :is_completion, :is_castration, images: [])
  end
  
end

app/helpers/admin/rescued_cats_helper.rb
module Admin::RescuedCatsHelper
end

app/views/admin/rescued_cats/index.html.erb
<div class="container mt-5">
  <h1 class="text-center ">里親募集一覧</h1>
    <h3 class = "text-right mb-3">
      <%= link_to "コメント一覧へ", admin_rescued_cat_rescued_cat_comments_path(:rescued_cat_id), class: "btn btn-sm btn-info" %>
    </h3>
    
    <div class="row">
      <% @rescued_cats.each do |rescued_cat| %>
        <div class="col-md-3 mb-4">
          <div class="card">
            <div class="card-header text-center">
              <%= link_to rescued_cat_path(rescued_cat.id) do %>
                <p class="card-title"><%= rescued_cat.title %></p>
              <% end %>
            </div>
  
            <% if rescued_cat.images.attached? %>
              <%= link_to rescued_cat_path(rescued_cat.id) do %>
                <%= image_tag rescued_cat.images.first, class: "card-img-top", alt: "Cat Image", size: "100x200" %>
              <% end %>
            <% end %>
  
            <div class="card-body">
              <p><%= image_tag rescued_cat.user.get_profile_image(50,50), class: "mr-3 rounded-circle" %>
                <%= link_to admin_user_path(rescued_cat.user.id) do %>
                  <%= rescued_cat.user.nickname %>
                 <% end %>
              </p>
               <small><%= truncate(rescued_cat.body, :length => 30) %></small>
              <p class = "justify-content-end">
               <%= link_to "削除", admin_rescued_cat_path(rescued_cat), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に削除しますか？" %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
      
    </div>
  
     <div class="row justify-content-center ">
      <div class="col-4 ">
        <%= paginate @rescued_cats %>
      </div>
    </div>

</div>
 