config/routes.rb
Rails.application.routes.draw do
    
  namespace :public do
    get 'chats/show'
  end
  root to: "homes#top"
  get "home/about"=>"homes#about"
  
   #ゲストユーザー用
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end   
 
 
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
    
    namespace :admin do
      
      resources :users, only: [:index, :show, :edit, :update]
      
      resources :diaries, only: [:index, :destroy] do
        resources :diary_comments, only: [:index, :destroy]
      end
      
      resources :rescued_cats, only: [:index, :destroy] do
        resources :rescued_cat_comments, only: [:index, :destroy]
      end
     
    end
    
   
   
    
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
    
    scope module: :public do
     
      get 'users/confirm_withdraw' => 'users#confirm_withdraw'
      patch 'users/withdraw' => 'users#withdraw'
      
      resources :users, only: [:show, :edit, :update] do
         member do
           get :favorites 
           get :bookmarks
           get :diaries
           get :cats
           get :rescued_cats
           get :my_page
           get :follows, :followers
         end
           resource :relationships, only: [:create, :destroy]
      end
      
      resources :chats, only: [:show, :create, :destroy]
      resources :cats, only: [:new, :create, :update, :show, :edit] 
      resources :notifications, only: [:update]
      
      resources :diaries do
         resource :favorite, only: [:create, :destroy]
         resources :diary_comments, only: [:create, :destroy]
          collection do
            get 'search'
            get 'tag_search'
          end
      end
      
      resources :rescued_cats do
         resource :bookmark, only: [:create, :destroy]
         resources :rescued_cat_comments, only: [:create, :destroy]
         collection do
            get 'search'
            get 'label_search'
         end
      end
   
      
    end 
 
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<div class="text-center">
  <% if obj.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h3 class="text-black"><%= obj.errors.count %> 件のエラーがあります</h3>
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class= "py-3" style="background-color: #8fbc8f;" >
    	<div class='row'>
      	<div class='mx-auto'>
      		<p>purrfect hub</p>
      	</div>
      </div>
</footer>

app/views/layouts/_header.html.erb
<header class="py-3 border-bottom " style="background-color:  #eae1bd;">
    <div class="container d-flex justify-content-center align-items-center ">
        <form class="col-12 col-lg-auto mb-3 mb-lg-0">
            <a class="navbar" href="/"><span><%= image_tag 'logo.png', size: "300x100" %></span></a>
        </form>

        <div>
            <% if user_signed_in? %>
                <%= image_tag current_user.get_profile_image(100, 100), class: "rounded-circle" %>
            <% elsif admin_signed_in? %>
                <h5 class="text-right">管理者でログインしています</h5>
            <% else %>
            <% end %>
        </div>
         <% if user_signed_in? %>
           <div class = "ml-3">
              <%= render 'layouts/notification' %>
           </div>
         <% end %>
    </div>
</header>
  <nav class="py-1 bg-body-tertiary border-bottom sticky-top" style="background-color: #deb887;">
    <div class="container d-flex flex-wrap justify-content-center ">
       <ul class="nav me-auto ">

                  <% if admin_signed_in? %>
                  <!--admin側ログイン後のheaderを返す-->
                      <%= link_to root_path, class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-house"></i> トップ<% end %>
                      <%= link_to admin_users_path, class:"btn btn-outline-dark m-1" do %><i class="fa-solid fa-users"></i> 会員一覧<% end %>
                      <%= link_to admin_diaries_path, class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-book-open"></i> みんなの日記<% end %>
                      <%= link_to admin_rescued_cats_path, class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-paw"></i> 里親募集<% end %>
                      <%= link_to destroy_admin_session_path, method: :delete, class:"btn btn-outline-dark m-1" do %><i class="fa-solid fa-person-running"></i> ログアウト<% end %>
                  <% elsif user_signed_in? %>
                  <!--userログイン後のheaderを返す  -->
                      <%= link_to root_path, class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-house"></i> トップ<% end %>
                      <%= link_to home_about_path, class: "btn btn-outline-dark m-1" do %><i class="fa-regular fa-circle-question"></i> アバウト<% end %>
                      <%= link_to rescued_cats_path, class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-paw"></i> 里親募集 <% end %>
                      <%= link_to diaries_path, class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-book-open"></i> みんなの日記 <% end %>
                      <%= link_to my_page_user_path(current_user), class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-user"></i> マイページ<% end %>
                      <%= link_to destroy_user_session_path, method: :delete, class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-person-running"></i> ログアウト<% end %>
                  <% else %>
                  <!--ログインしていない時に表示するheaderのメニューを記載-->
                      <%= link_to root_path, class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-house"></i> トップ<% end %>
                      <%= link_to home_about_path, class: "btn btn-outline-dark m-1" do %><i class="fa-regular fa-circle-question"></i> アバウト<% end %>
                      <%= link_to rescued_cats_path, class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-paw"></i> 里親募集 <% end %>
                      <%= link_to diaries_path, class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-book-open"></i> みんなの日記 <% end %>
                      <%= link_to new_user_registration_path, class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-user-plus"></i> 新規会員登録 <% end %>
                      <%= link_to new_user_session_path, class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-right-to-bracket"></i> ログイン<% end %>
                      <%= link_to users_guest_sign_in_path, method: :post, class: "btn btn-outline-dark m-1" do %><i class="fa-solid fa-user-secret"></i> ゲストログイン<% end %>
                  <% end %>
      </ul>
    </div>
  </nav>
  

app/views/layouts/_notification.html.erb
  <div class="dropdown" style="position: relative; z-index: 2000;">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa-sharp fa-solid fa-bell"></i>
        <span class="badge badge-danger"><%= current_user.notifications.where(read: false).count %></span>
    </button>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="position: absolute; left: 0; right: 0; width: 500px;">
        <% if current_user.notifications.where(read: false).any? %>
            <small class="dropdown-item disabled">直近5件の未読の通知を表示しています</small>
            <% current_user.notifications.where(read: false).limit(5).order(created_at: :desc).each do |notification| %>
                <%= link_to truncate(notification.message, :length => 12),notification, method: :patch, class: "dropdown-item" %>
            <% end %>
        <% else %>
            <span class="dropdown-item disabled">未読の通知はありません</span>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Purrfecthub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/2b1770b765.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
  </head>


 <body>
    
   
  <%= render 'layouts/header' %>

  <main class= "py-3" style="background-color: #eae1bd;">
    <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    
    <%= yield %>
  </main>

  <%= render 'layouts/footer' %>
</body>